# Generated by Django 3.1.3 on 2021-01-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '__first__'),
        ('accounts', '0004_auto_20210115_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.category'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(related_name='candidaties', to='job.Job'),
        ),
    ]
