# Generated by Django 3.1.3 on 2021-01-18 09:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '__first__'),
        ('accounts', '0006_auto_20210117_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_company_image),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.upload_cv),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='candidaties', to='job.Job'),
        ),
    ]
