# Generated by Django 3.1.3 on 2021-01-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210118_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='cover_letter',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(default='this is my bio', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Web Developer', max_length=13),
            preserve_default=False,
        ),
    ]
