# Generated by Django 3.1.3 on 2021-01-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20201222_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='author',
            new_name='company',
        ),
    ]
